[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

# Add the plugin to install function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Redirect /images/filename.jpeg to the serverless function
[[redirects]]
  from = "/images/*"
  to = "/.netlify/functions/get-image"
  status = 200
  force = true

# Additional rule for direct function access
[[redirects]]
  from = "/.netlify/functions/get-image/*"
  to = "/.netlify/functions/get-image"
  status = 200
  force = true 